# Generated by Django 5.2.5 on 2025-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_follower', 'New Follower'), ('like', 'Music Like'), ('comment', 'Music Comment'), ('new_music', 'New Music Upload')], max_length=20),
        ),
    ]
