# Generated by Django 5.2.5 on 2025-08-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_played_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.music'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='playback_position',
            field=models.FloatField(default=0.0),
        ),
    ]
